/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteElectionIdRouteImport } from './routes/vote.$electionId'
import { Route as ResultsElectionIdRouteImport } from './routes/results.$electionId'
import { Route as OSlugRouteImport } from './routes/o.$slug'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedAppOrganizationsRouteImport } from './routes/_authenticated/app.organizations'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppOrganizationsOrgIdRouteImport } from './routes/_authenticated/app.organizations.$orgId'
import { Route as AuthenticatedAppElectionsElectionIdRouteImport } from './routes/_authenticated/app.elections.$electionId'
import { Route as ApiPublicOrgsSlugMembersRouteImport } from './routes/api/public/orgs.$slug.members'
import { Route as AuthenticatedAppElectionsElectionIdResultsRouteImport } from './routes/_authenticated/app.elections.$electionId.results'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteElectionIdRoute = VoteElectionIdRouteImport.update({
  id: '/vote/$electionId',
  path: '/vote/$electionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsElectionIdRoute = ResultsElectionIdRouteImport.update({
  id: '/results/$electionId',
  path: '/results/$electionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppOrganizationsRoute =
  AuthenticatedAppOrganizationsRouteImport.update({
    id: '/app/organizations',
    path: '/app/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppOrganizationsOrgIdRoute =
  AuthenticatedAppOrganizationsOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedAppOrganizationsRoute,
  } as any)
const AuthenticatedAppElectionsElectionIdRoute =
  AuthenticatedAppElectionsElectionIdRouteImport.update({
    id: '/app/elections/$electionId',
    path: '/app/elections/$electionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicOrgsSlugMembersRoute =
  ApiPublicOrgsSlugMembersRouteImport.update({
    id: '/api/public/orgs/$slug/members',
    path: '/api/public/orgs/$slug/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppElectionsElectionIdResultsRoute =
  AuthenticatedAppElectionsElectionIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedAppElectionsElectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/methods': typeof MethodsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/use-cases': typeof UseCasesRoute
  '/my': typeof AuthenticatedMyRoute
  '/o/$slug': typeof OSlugRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/vote/$electionId': typeof VoteElectionIdRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/organizations': typeof AuthenticatedAppOrganizationsRouteWithChildren
  '/app/elections/$electionId': typeof AuthenticatedAppElectionsElectionIdRouteWithChildren
  '/app/organizations/$orgId': typeof AuthenticatedAppOrganizationsOrgIdRoute
  '/app/elections/$electionId/results': typeof AuthenticatedAppElectionsElectionIdResultsRoute
  '/api/public/orgs/$slug/members': typeof ApiPublicOrgsSlugMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/methods': typeof MethodsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/use-cases': typeof UseCasesRoute
  '/my': typeof AuthenticatedMyRoute
  '/o/$slug': typeof OSlugRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/vote/$electionId': typeof VoteElectionIdRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/organizations': typeof AuthenticatedAppOrganizationsRouteWithChildren
  '/app/elections/$electionId': typeof AuthenticatedAppElectionsElectionIdRouteWithChildren
  '/app/organizations/$orgId': typeof AuthenticatedAppOrganizationsOrgIdRoute
  '/app/elections/$electionId/results': typeof AuthenticatedAppElectionsElectionIdResultsRoute
  '/api/public/orgs/$slug/members': typeof ApiPublicOrgsSlugMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/methods': typeof MethodsRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/use-cases': typeof UseCasesRoute
  '/_authenticated/my': typeof AuthenticatedMyRoute
  '/o/$slug': typeof OSlugRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/vote/$electionId': typeof VoteElectionIdRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/organizations': typeof AuthenticatedAppOrganizationsRouteWithChildren
  '/_authenticated/app/elections/$electionId': typeof AuthenticatedAppElectionsElectionIdRouteWithChildren
  '/_authenticated/app/organizations/$orgId': typeof AuthenticatedAppOrganizationsOrgIdRoute
  '/_authenticated/app/elections/$electionId/results': typeof AuthenticatedAppElectionsElectionIdResultsRoute
  '/api/public/orgs/$slug/members': typeof ApiPublicOrgsSlugMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/features'
    | '/login'
    | '/methods'
    | '/pricing'
    | '/security'
    | '/use-cases'
    | '/my'
    | '/o/$slug'
    | '/results/$electionId'
    | '/vote/$electionId'
    | '/app/dashboard'
    | '/app/organizations'
    | '/app/elections/$electionId'
    | '/app/organizations/$orgId'
    | '/app/elections/$electionId/results'
    | '/api/public/orgs/$slug/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/features'
    | '/login'
    | '/methods'
    | '/pricing'
    | '/security'
    | '/use-cases'
    | '/my'
    | '/o/$slug'
    | '/results/$electionId'
    | '/vote/$electionId'
    | '/app/dashboard'
    | '/app/organizations'
    | '/app/elections/$electionId'
    | '/app/organizations/$orgId'
    | '/app/elections/$electionId/results'
    | '/api/public/orgs/$slug/members'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/features'
    | '/login'
    | '/methods'
    | '/pricing'
    | '/security'
    | '/use-cases'
    | '/_authenticated/my'
    | '/o/$slug'
    | '/results/$electionId'
    | '/vote/$electionId'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/organizations'
    | '/_authenticated/app/elections/$electionId'
    | '/_authenticated/app/organizations/$orgId'
    | '/_authenticated/app/elections/$electionId/results'
    | '/api/public/orgs/$slug/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  MethodsRoute: typeof MethodsRoute
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
  UseCasesRoute: typeof UseCasesRoute
  OSlugRoute: typeof OSlugRoute
  ResultsElectionIdRoute: typeof ResultsElectionIdRoute
  VoteElectionIdRoute: typeof VoteElectionIdRoute
  ApiPublicOrgsSlugMembersRoute: typeof ApiPublicOrgsSlugMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$electionId': {
      id: '/vote/$electionId'
      path: '/vote/$electionId'
      fullPath: '/vote/$electionId'
      preLoaderRoute: typeof VoteElectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$electionId': {
      id: '/results/$electionId'
      path: '/results/$electionId'
      fullPath: '/results/$electionId'
      preLoaderRoute: typeof ResultsElectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/organizations': {
      id: '/_authenticated/app/organizations'
      path: '/app/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AuthenticatedAppOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/organizations/$orgId': {
      id: '/_authenticated/app/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/app/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedAppOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationsRoute
    }
    '/_authenticated/app/elections/$electionId': {
      id: '/_authenticated/app/elections/$electionId'
      path: '/app/elections/$electionId'
      fullPath: '/app/elections/$electionId'
      preLoaderRoute: typeof AuthenticatedAppElectionsElectionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/orgs/$slug/members': {
      id: '/api/public/orgs/$slug/members'
      path: '/api/public/orgs/$slug/members'
      fullPath: '/api/public/orgs/$slug/members'
      preLoaderRoute: typeof ApiPublicOrgsSlugMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/elections/$electionId/results': {
      id: '/_authenticated/app/elections/$electionId/results'
      path: '/results'
      fullPath: '/app/elections/$electionId/results'
      preLoaderRoute: typeof AuthenticatedAppElectionsElectionIdResultsRouteImport
      parentRoute: typeof AuthenticatedAppElectionsElectionIdRoute
    }
  }
}

interface AuthenticatedAppOrganizationsRouteChildren {
  AuthenticatedAppOrganizationsOrgIdRoute: typeof AuthenticatedAppOrganizationsOrgIdRoute
}

const AuthenticatedAppOrganizationsRouteChildren: AuthenticatedAppOrganizationsRouteChildren =
  {
    AuthenticatedAppOrganizationsOrgIdRoute:
      AuthenticatedAppOrganizationsOrgIdRoute,
  }

const AuthenticatedAppOrganizationsRouteWithChildren =
  AuthenticatedAppOrganizationsRoute._addFileChildren(
    AuthenticatedAppOrganizationsRouteChildren,
  )

interface AuthenticatedAppElectionsElectionIdRouteChildren {
  AuthenticatedAppElectionsElectionIdResultsRoute: typeof AuthenticatedAppElectionsElectionIdResultsRoute
}

const AuthenticatedAppElectionsElectionIdRouteChildren: AuthenticatedAppElectionsElectionIdRouteChildren =
  {
    AuthenticatedAppElectionsElectionIdResultsRoute:
      AuthenticatedAppElectionsElectionIdResultsRoute,
  }

const AuthenticatedAppElectionsElectionIdRouteWithChildren =
  AuthenticatedAppElectionsElectionIdRoute._addFileChildren(
    AuthenticatedAppElectionsElectionIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMyRoute: typeof AuthenticatedMyRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppOrganizationsRoute: typeof AuthenticatedAppOrganizationsRouteWithChildren
  AuthenticatedAppElectionsElectionIdRoute: typeof AuthenticatedAppElectionsElectionIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMyRoute: AuthenticatedMyRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppOrganizationsRoute:
    AuthenticatedAppOrganizationsRouteWithChildren,
  AuthenticatedAppElectionsElectionIdRoute:
    AuthenticatedAppElectionsElectionIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  MethodsRoute: MethodsRoute,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
  UseCasesRoute: UseCasesRoute,
  OSlugRoute: OSlugRoute,
  ResultsElectionIdRoute: ResultsElectionIdRoute,
  VoteElectionIdRoute: VoteElectionIdRoute,
  ApiPublicOrgsSlugMembersRoute: ApiPublicOrgsSlugMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
